In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the volcabulary size
voc_size = 10000

In [8]:
# one_hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6564, 5730, 5543, 8824],
 [6564, 5730, 5543, 3947],
 [6564, 4706, 5543, 7591],
 [2297, 2721, 3894, 3192, 9756],
 [2297, 2721, 3894, 3192, 7270],
 [8952, 6564, 4276, 5543, 2599],
 [228, 4278, 6907, 3192]]

In [14]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as np

In [21]:
sent_length = 8
embedding_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedding_docs)

[[   0    0    0    0 6564 5730 5543 8824]
 [   0    0    0    0 6564 5730 5543 3947]
 [   0    0    0    0 6564 4706 5543 7591]
 [   0    0    0 2297 2721 3894 3192 9756]
 [   0    0    0 2297 2721 3894 3192 7270]
 [   0    0    0 8952 6564 4276 5543 2599]
 [   0    0    0    0  228 4278 6907 3192]]


In [22]:
#Feature Representation
dim = 10

In [25]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile(optimizer='adam', loss='categorical_crossentropy')

In [ ]:
model.build(input_shape=(None, sent_length)) 

In [28]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)